#!/usr/bin/env python3
from msw import GeographicViz


def main():
    """Command line tool to generate today's geographic surf forecast visualisation."""
    viz = GeographicViz()
    viz.save_and_open()


if __name__ == "__main__":
    main()
